# fly.toml app configuration file generated for weather-signature on 2024-12-19T02:32:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weather-signature'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
